// TO ADD A USER
// METHOD: Post
// ROUTE: /user/create

// REQ.BODY:
export interface AddUserType {
  // id: number; autogenerated in db
  username: string;
  email: string;
  password: string;
  // created_at: timestamp; default in db
  countrycodes: string[];
}

// TO GET A USER'S COUNTRY CODES:
// METHOD: Get
// ROUTE: /user/get

// REQ.BODY:
export interface GetUserType {
  username: string;
}

// RES.BODY:
export type GetAllCCType = string[];

// TO UPDATE A USER'S COUNTRY CODES:
// METHOD: POST
// ROUTE: /locations/update

// REQ.BODY:
export interface AddLocationBodyType {
  username: string;
  countrycodes: string[];
}

// RES.BODY:
export type AddAndGetCCType = string[];
