// 1] <ref *2> IncomingMessage {
//   [1]   
//   [1]   _events: [Object: null prototype] { end: [Function: clearRequestTimeout] },
//   [1]   _eventsCount: 1,
//   [1]   _maxListeners: undefined,
//   [1]   socket:
//   [1]   httpVersionMajor: 1,
//   [1]   httpVersionMinor: 1,
//   [1]   httpVersion: '1.1',
//   [1]   complete: true,
//   [1]   headers: {
//   [1]     host: 'localhost:3000',
//   [1]     connection: 'keep-alive',
//   [1]     dnt: '1',
//   [1]     'upgrade-insecure-requests': '1',
//   [1]     'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36',
//   [1]     accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
//   [1]     purpose: 'prefetch',
//   [1]     'sec-fetch-site': 'none',
//   [1]     'sec-fetch-mode': 'navigate',
//   [1]     'sec-fetch-user': '?1',
//   [1]     'sec-fetch-dest': 'document',
//   [1]     'accept-encoding': 'gzip, deflate, br',
//   [1]     'accept-language': 'en-US,en;q=0.9'
//   [1]   },
//   [1]   rawHeaders: [
//   [1]     'Host',
//   [1]     'localhost:3000',
//   [1]     'Connection',
//   [1]     'keep-alive',
//   [1]     'DNT',
//   [1]     '1',
//   [1]     'Upgrade-Insecure-Requests',
//   [1]     '1',
//   [1]     'User-Agent',
//       'Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36',
//   [1]     'Accept',
//   [1]     'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
//   [1]     'Purpose',
//   [1]     'prefetch',
//   [1]     'Sec-Fetch-Site',
//   [1]     'none',
//   [1]     'Sec-Fetch-Mode',
//   [1]     'navigate',
//   [1]     'Sec-Fetch-User',
//   [1]     '?1',
//   [1]     'Sec-Fetch-Dest',
//   [1]     'document',
//   [1]     'Accept-Encoding',
//   [1]     'gzip, deflate, br',
//   [1]     'Accept-Language',
//   [1]     'en-US,en;q=0.9'
//   [1]   ],
//   [1]   trailers: {},
//   [1]   rawTrailers: [],
//   [1]   aborted: false,
//   [1]   upgrade: false,
//   [1]   url: '/auth/facebook/callback?code=AQDYBZsvXJhqHIOSAMnDliKLYwQ22NJ496GWBbs9VQWhc3XZ3luH7_1ZVemStEKHWK0EfH6kz1X4LG7LX9_bUuYeOE81CWeXeigFGUNSYdSrFZ8adjwen37cySMDCuMgK2Y5_qQpO1OZOGYDec_w9nRmo5ycrg5qoz3zmSBOUrsq_pvrhWysVQmJ48Yphwv4V_f055u7Ab1dDA9TXzTzrq3bv094Fjyln_7qpm-WQl1PGIorxrL4wqxwGxpzos5O1oNmQo0Qbtem_arkoi238DmSLFznli3SFnZSd5nR2XK4r-UkOhCuf-4XfT1LfeQM8cSHBo_tZDD25XlUXdee6vznjEJHmSTBwFznfpnKWbClgQ',
//   [1]   method: 'GET',
//   [1]   statusCode: null,
//   [1]   statusMessage: null,
//   [1]   client: <ref *1> Socket {
//   [1]     connecting: false,
//   [1]     _hadError: false,
//   [1]     _parent: null,
//   [1]     _host: null,
//   [1]     _readableState: 
//   [1]     _events: 
//   [1]     _eventsCount: 8,
//   [1]     _maxListeners: undefined,
//   [1]     _writableState: 
//   [1]     allowHalfOpen: true,
//   [1]     _sockname: null,
//   [1]     _pendingData: null,
//   [1]     _pendingEncoding: '',
//   [1]     server: 
//   [1]     _server: 
//   [1]     parser: 
//   [1]     on: [Function: socketListenerWrap],
//   [1]     addListener: [Function: socketListenerWrap],
//   [1]     prependListener: [Function: socketListenerWrap],
//   [1]     _paused: false,
//   [1]     _httpMessage: ServerResponse {
//   [1]       _events: [Object: null prototype],
//   [1]       _eventsCount: 1,
//   [1]       _maxListeners: undefined,
//   [1]       outputData: [],
//   [1]       outputSize: 0,
//   [1]       writable: true,
//   [1]       destroyed: false,
//   [1]       _last: false,
//   [1]       chunkedEncoding: false,
//   [1]       shouldKeepAlive: true,
//   [1]       _defaultKeepAlive: true,
//   [1]       useChunkedEncodingByDefault: true,
//   [1]       sendDate: true,
//   [1]       _removedConnection: false,
//   [1]       _removedContLen: false,
//   [1]       _removedTE: false,
//   [1]       _contentLength: null,
//   [1]       _hasBody: true,
//   [1]       _trailer: '',
//   [1]       finished: false,
//   [1]       _headerSent: false,
//   [1]       socket: [Circular *1],
//   [1]       _header: null,
//   [1]       _keepAliveTimeout: 5000,
//   [1]       _onPendingData: [Function: bound updateOutgoingData],
//   [1]       _sent100: false,
//   [1]       _expect_continue: false,
//   [1]       req: [Circular *2],
//   [1]       locals: [Object: null prototype] {},
//   [1]       [Symbol(kCapture)]: false,
//   [1]       [Symbol(kNeedDrain)]: false,
//   [1]       [Symbol(corked)]: 0,
//   [1]       [Symbol(kOutHeaders)]: [Object: null prototype]
//   [1]     },
//   [1]     timeout: 0,
//   [1]     [Symbol(async_id_symbol)]: 8,
//   [1]     [Symbol(kHandle)]: TCP {
//   [1]       reading: true,
//   [1]       onconnection: null,
//   [1]       _consumed: true,
//   [1]       [Symbol(owner_symbol)]: [Circular *1]
//   [1]     },
//   [1]     [Symbol(kSetNoDelay)]: false,
//   [1]     [Symbol(lastWriteQueueSize)]: 0,
//   [1]     [Symbol(timeout)]: Timeout {
//   [1]       _idleTimeout: -1,
//   [1]       _idlePrev: null,
//   [1]       _idleNext: null,
//   [1]       _idleStart: 17489,
//   [1]       _onTimeout: null,
//   [1]       _timerArgs: undefined,
//   [1]       _repeat: null,
//   [1]       _destroyed: true,
//   [1]       [Symbol(refed)]: false,
//   [1]       [Symbol(kHasPrimitive)]: false,
//   [1]       [Symbol(asyncId)]: 17,
//   [1]       [Symbol(triggerId)]: 14
//   [1]     },
//   [1]     [Symbol(kBuffer)]: null,
//   [1]     [Symbol(kBufferCb)]: null,
//   [1]     [Symbol(kBufferGen)]: null,
//   [1]     [Symbol(kCapture)]: false,
//   [1]     [Symbol(kBytesRead)]: 0,
//   [1]     [Symbol(kBytesWritten)]: 0,
//   [1]     [Symbol(RequestTimeout)]: undefined
//   [1]   },
//   [1]   _consuming: false,
//   [1]   _dumped: false,
//   [1]   next: [Function: next],
//   [1]   baseUrl: '',
//   [1]   originalUrl: '/auth/facebook/callback?code=AQDYBZsvXJhqHIOSAMnDliKLYwQ22NJ496GWBbs9VQWhc3XZ3luH7_1ZVemStEKHWK0EfH6kz1X4LG7LX9_bUuYeOE81CWeXeigFGUNSYdSrFZ8adjwen37cySMDCuMgK2Y5_qQpO1OZOGYDec_w9nRmo5ycrg5qoz3zmSBOUrsq_pvrhWysVQmJ48Yphwv4V_f055u7Ab1dDA9TXzTzrq3bv094Fjyln_7qpm-WQl1PGIorxrL4wqxwGxpzos5O1oNmQo0Qbtem_arkoi238DmSLFznli3SFnZSd5nR2XK4r-UkOhCuf-4XfT1LfeQM8cSHBo_tZDD25XlUXdee6vznjEJHmSTBwFznfpnKWbClgQ',
//   [1]   _parsedUrl: 
//   [1]   params: {},
//   [1]   query: {
//   [1]     code: 'AQDYBZsvXJhqHIOSAMnDliKLYwQ22NJ496GWBbs9VQWhc3XZ3luH7_1ZVemStEKHWK0EfH6kz1X4LG7LX9_bUuYeOE81CWeXeigFGUNSYdSrFZ8adjwen37cySMDCuMgK2Y5_qQpO1OZOGYDec_w9nRmo5ycrg5qoz3zmSBOUrsq_pvrhWysVQmJ48Yphwv4V_f055u7Ab1dDA9TXzTzrq3bv094Fjyln_7qpm-WQl1PGIorxrL4wqxwGxpzos5O1oNmQo0Qbtem_arkoi238DmSLFznli3SFnZSd5nR2XK4r-UkOhCuf-4XfT1LfeQM8cSHBo_tZDD25XlUXdee6vznjEJHmSTBwFznfpnKWbClgQ'
//   [1]   },
//   [1]   res: 
//   [1]   body: {},
//   [1]   _parsedOriginalUrl:
//   [1]   _passport: {
//   [1]     instance: Authenticator {
//   [1]       _key: 'passport',
//   [1]       _strategies: [Object],
//   [1]       _serializers: [Array],
//   [1]       _deserializers: [Array],
//   [1]       _infoTransformers: [],
//   [1]       _framework: [Object],
//   [1]       _userProperty: 'user',
//   [1]       _sm: [SessionManager],
//   [1]       Authenticator: [Function: Authenticator],
//   [1]       Passport: [Function: Authenticator],
//   [1]       Strategy: [Function],
//   [1]       strategies: [Object]
//   [1]     },
//   [1]     session: { user: [Object] }
//   [1]   },
//   [1]   route: Route {
//   [1]     path: '/auth/facebook/callback',
//   [1]     stack: [ [Layer], [Layer] ],
//   [1]     methods: { get: true }
//   [1]   },
//   [1]   user: {
//   [1]     id: 33,
//   [1]     username: 'Anson Avellar',
//   [1]     password: 'EAALkBzvQSrEBAHVSjQwXsZAzjF3SRraeeJl9AOPaumGhsZC9WloiXqZA1EZBhdl2zZAg4NNnnPtj0tRZC1AqG8Nr7UEqPRS0RCUo5TjZBofoM85ysEyyFfpYZAGSF6ZBkSuuQ8hT8ZCC2ca3X9vkBAup1zPwXhJrrpt9AZD',
//   [1]     created_at: 2021-03-04T01:10:10.248Z,
//   [1]     countrycodes: null,
//   [1]     facebook_id: '10102684037050041',
//   [1]     email: null
//   [1]   },
//   [1]   session: { passport: { user: [Object] } },
//   [1]   authInfo: {},
//   [1]   [Symbol(kCapture)]: false,
//   [1]   [Symbol(RequestTimeout)]: undefined
//   [1] }