// const db = require()

// defining our userController object
const userController = {};

// Table: user
// {
//   id: (autogenerated) Primary Key
//   username: string,
//   email: string,
//   password: string,
// }

// add new user
userController.addUser = (req, res, next) => {
  const { username, email, password } = req.body;

  const postQuery = `
    INSERT INTO user (username, email, password)
    VALUES ($1, $2, $3)
  `;

  const queryParams = [username, email, password];

  db.query(postQuery, queryParams)
    .then((data) => {
      console.log('Successfully added to db!');
      res.locals.newUser = data.rows[0];
      return next();
    })
    .catch((err: any) => {
      next({ log: `userController.addUser ERROR: ${err}` });
    });
};

module.exports = userController;
